### ISSUE TITLE
How can I make it work in pdfjs

### ISSUE THREAD

**Issue by amosbird** [zotero/zotero-connectors#103]
I know chrome has limits that prevent extensions from accessing each other. I wonder if there is a way to slightly modify `pdfjs` so that it can save current viewing pdf to zotero.

**Comment by adomasven** [comment]
I am not entirely sure what you're looking for here, but the connector can already save the currently viewed pdf by clicking the connector icon.

Also note that this issue tracker is used for development issues. If you want to discuss something code specific you should post at our [mailing list](https://groups.google.com/forum/#!forum/zotero-dev).
