### ISSUE TITLE
Check Firefox 45 compatibility

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#107]
Reported here: https://forums.zotero.org/discussion/comment/272132/#Comment_272132

**Comment by adomasven** [comment]
While may be possible, FX45 compatibility is completely inpractical. Quoting a Mozilla article regarding [webext in FX46](https://blog.mozilla.org/addons/2016/02/02/webextensions-in-firefox-46/):

> "While WebExtensions will remain in an alpha state in Firefox 46, we’ve made lots of progress, with 40 bugs closed since the last update. As of this update, we are still on track for a milestone release in Firefox 48 when it hits Developer Edition.

By the looks of it FX45 doesn't even have support for connector preferences, making it no better than the bookmarklet, if we can even get it to work. We will have to point people on ESR to the bookmarklet and/or not upgrade them from Zotero 4.0
