### ISSUE TITLE
Cross-site processDocuments() fails in Firefox

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#108]
1) Modify the "Gemeinsamer Bibliotheksverbund ISBN" translator to return false from `detectSearch()` in the data directory, restart Zotero, and reset translators in the Firefox connector.

2) Try to save from https://www.amazon.com/dp/0099590085/

It fails (and hangs) in Firefox with a security error in the Web Console:

```
DOMException [SecurityError: "The operation is insecure."
code: 18
nsresult: 0x80530012
location: file:///Users/dan/Development/Zotero/Connectors/build/browserExt/inject/http.js:191]
```
This is from [onCrossSiteLoad](https://github.com/zotero/zotero-connectors/blob/c56ef5a27a187b98ffa98c85056cfa96d697e1b5/src/common/inject/http.js#L181) in common/inject/http.js.

This works in Chrome.

**Comment by adomasven** [comment]
Notify https://forums.zotero.org/discussion/64990/5-0-beta-translators-not-working-chromium-firefox upon new connector version rollout.
