### ISSUE TITLE
"Cannot send function call result: other side closed connection" in Firefox

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#110]
With Firefox 52.0.2 and 39cd61ddff323cf046f97d9afe7e9bd63209ad3d, load https://scholar.google.com/scholar?hl=en&q=test&btnG=&as_sdt=1%2C33&as_sdtp=, click save button, select top item, save.

Save works, but I get the above message in the console.

**Comment by dstillman** [comment]
Actually, I'm getting all sorts of errors. Just loading that GS page with the connector enabled:

> uncaught exception: 0  (unknown)

> Unchecked lastError value: Error: Script returned non-structured-clonable data ExtensionCommon.jsm:265

First one only appears if Zotero is closed. Both go away if the extension is disabled.

**Comment by adomasven** [comment]
The errors appear to be harmless and there is no easy way to track them down, because the traces do not include the source of the error - only firefox jsm files. There is a [ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1339559) on bugzilla to address at least one of these, fix available with FX 55

Otherwise I don't think it's worth to spend too much effort on this for now.

**Comment by dstillman** [comment]
The "fix" for 55 is just to identify the script that triggered the error, so it should be possible to see the better message in Nightly. And I think this is new, so a bisect should also be helpful. We can't spam the console on every page load. (Among other things, Mozilla will complain.)

**Comment by adomasven** [comment]
> The "fix" for 55 is just to identify the script that triggered the error, so it should be possible to see the better message in Nightly

Well yes. I can look into `Unchecked lastError value: Error: Script returned non-structured-clonable data ExtensionCommon.jsm:265`, but that's just one of these cryptic errors.

> Among other things, Mozilla will complain.

Do you think this would be grounds for not passing their validation process? If not, I think the time looking for workarounds around firefox issues is better spent elsewhere.

**Comment by adomasven** [comment]
No longer present.
