### ISSUE TITLE
If proxy redirects to unproxied site, Zotero should not attempt to redirect again

### ISSUE THREAD

**Issue by simonster** [zotero/zotero-connectors#111]
When I'm on campus, attempting to access a site through the MIT proxy will result in the proxy redirecting me back to the original site. After the proxy redirects me to the original site, the Firefox connector is trying to send me back through the proxy, e.g.:

```
connector => true, version => 4.999.17, platform => MacIntel, locale => en-US, userAgent => Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0, appName => Firefox Connector, zoteroAvailable => true

=========================================================

(3)(+0005439): Proxies.properToProxy: http://science.sciencemag.org/content/353/6301/757.full to http://science.sciencemag.org.libproxy.mit.edu/content/353/6301/757.full

(3)(+0000002): NOTIFICATION: science.sciencemag.org was automatically redirected through science.sciencemag.org.libproxy.mit.edu

(3)(+0000911): Proxies.properToProxy: http://science.sciencemag.org/content/353/6301/757.full to http://science.sciencemag.org.libproxy.mit.edu/content/353/6301/757.full

(3)(+0000001): NOTIFICATION: science.sciencemag.org was automatically redirected through science.sciencemag.org.libproxy.mit.edu

(3)(+0001102): Proxies.properToProxy: http://science.sciencemag.org/content/353/6301/757.full to http://science.sciencemag.org.libproxy.mit.edu/content/353/6301/757.full

(3)(+0000001): NOTIFICATION: science.sciencemag.org was automatically redirected through science.sciencemag.org.libproxy.mit.edu

...
```

Eventually, Firefox gives up and shows me a "The page isn’t redirecting properly" message, and I can't get to the page without turning off proxy redirection. There is [code](https://github.com/zotero/zotero-connectors/blob/b87084cd5cccd7527b0023469685e34f25056e13/src/common/proxy.js#L211-L224) to handle this case, and it works fine as implemented in classic Zotero for Firefox, but it doesn't seem to be working in the WebExtension.

**Comment by adomasven** [comment]
I'm afraid I have no way to test this and looking at the code I cannot see any problems with it. It was ported without any changes from the original one and walking through it in my head seems like it should work, but it is obviously a huge problem, if it doesn't.

@dstillman can you provide me with, or figure out a setup for yourself to test this?
