### ISSUE TITLE
Zotero.HTTP does not support custom headers

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-connectors#122]
Required [in ORCID translator](https://github.com/zotero/translators/blob/ed21c7bdcccf91e076af4f564722d47893184dca/ORCID.js#L68-L76) to fetch CSL JSON instead of CSL XML

**Comment by dstillman** [comment]
(Only semi-related, and we can stuff support for this into the existing function in the interim, but we should probably just port `Zotero.HTTP.request()` from the client over to the connectors, relying on the native `Promise` in the bookmarklet, and deprecate `doGet/doPost` in translators. Of course, it would be nice to use `async`/`await` with that, but that might need to wait a bit longer.)

**Comment by adomasven** [comment]
I am mostly scared to touch this code without tests, but we should certainly switch to `Zotero.HTTP.request()`. Maybe in a follow-up issue though.
