### ISSUE TITLE
Add Zotero.HTTP.request() and deprecate doGet and doPost

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-connectors#123]
@dstillman in #122 :
> (Only semi-related, and we can stuff support for this into the existing function in the interim, but we should probably just port Zotero.HTTP.request() from the client over to the connectors, relying on the native Promise in the bookmarklet, and deprecate doGet/doPost in translators. Of course, it would be nice to use async/await with that, but that might need to wait a bit longer.)

**Comment by dstillman** [comment]
Done in https://github.com/zotero/zotero-connectors/commit/d52dab1b2932332bcb1faedbd633d775c38cbc6e
