### ISSUE TITLE
ZoteroItemsUpdated event

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-connectors#124]
Check if [ZoteroItemsUpdate](https://www.zotero.org/support/dev/exposing_metadata#force_zotero_to_refresh_metadata) is functional

**Comment by adomasven** [comment]
Possibly relevant https://forums.zotero.org/discussion/65608/zotero-5-0-ams-translators-dont-work-at-all

**Comment by adomasven** [comment]
Code looks fine, but we'd need an example of a page using this to make sure.

**Comment by fcheslack** [comment]
https://www.zotero.org/z_public_library/items
