### ISSUE TITLE
Multiple notification bars accessing ProQuest via proxy

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#127]
<img width="1045" alt="notifications" src="https://cloud.githubusercontent.com/assets/783082/26091289/405716ca-39d8-11e7-88e5-9053a6318414.png">

It would be nice to avoid this, if we can do so in a sensible manner.

**Comment by dstillman** [comment]
Zotero 4.0 for Firefox, for comparison:

<img width="1399" alt="notification" src="https://cloud.githubusercontent.com/assets/783082/26091450/55a8e160-39d9-11e7-80e4-74b9ff6d0f69.png">

**Comment by adomasven** [comment]
There's no non-semi-annoying way to deal with this. We should just sequentialize the notifications. Can't risk losing any, especially if later on we want to add them for non-proxy events.

**Comment by dstillman** [comment]
Meaning that once you dismiss one or the timeout occurs, the next one appears? That seems reasonable.
