### ISSUE TITLE
Attempting to install a style with Zotero closed shows "null" in progress window

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#132]
A red 'x' appears with "null" next to it. We should display a message that Zotero must be open.

(I didn't check if the same thing happens for RIS/BibTex.)

**Comment by adomasven** [comment]
For the record, if Zotero is closed, the prompt (and thus the progress window) to install into Zotero doesn't even normally appear. This only applies directly after you close Zotero and before the Connector pings Zotero to see if it's still available. Upon webrequest interception, if Zotero was last available, the prompt for importing is shown (as the webrequest intercept response has to be synchronous).

**Comment by dstillman** [comment]
Ah, even better — was wondering if that was possible, but I guess I didn't check.
