### ISSUE TITLE
Don't show notifications again if shown for x seconds

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#133]
…where `x` is…4? Hopefully more than enough time for the vast majority of JS redirects and short enough that if someone sees the notification and chooses to navigate to another page it won't show up again.

**Comment by adomasven** [comment]
This has been implemented [2 days ago](https://github.com/zotero/zotero-connectors/commit/04932de3a1b2c81a138a9c53de677f88d1781f86) with a timeout of 5 seconds.
