### ISSUE TITLE
Translator hang (regression)

### ISSUE THREAD

**Issue by fbennett** [zotero/zotero-connectors#134]
Testing in Chrome, we've hit a hang condition in the `Amazon.js` translator with the following URL:

https://www.amazon.co.jp/%E3%82%A2%E3%82%B8%E3%82%A2%E3%83%BB%E5%A4%AA%E5%B9%B3%E6%B4%8B%E5%9C%B0%E5%9F%9F%E3%81%AEESD-%E3%80%88%E6%8C%81%E7%B6%9A%E5%8F%AF%E8%83%BD%E3%81%AA%E9%96%8B%E7%99%BA%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E6%95%99%E8%82%B2%E3%80%89%E3%81%AE%E6%96%B0%E5%B1%95%E9%96%8B-%E9%98%BF%E9%83%A8-%E6%B2%BB/dp/4750335754

The translator attempts to fetch metadata for an ISBN extracted from the page (9784750335759) using a series of translators, beginning with `Library of Congress ISBN.js`. The LoC host and port called by that translator is inaccessible (from our domain, at least).

From commit 9391f36a1484c32fc20246c42a1532645c8bfabb (May 19), the translator does not proceed after failing on the first translator attempted, and the async process does not complete. A browser restart is needed to restore the operation of translators.

Prior to commit 9391f36a1484c32fc20246c42a1532645c8bfabb, the connector fails over successfully, ultimately obtaining RIS metadata.

Hope that helps (I looked at the commit, but I don't know enough about the translation infrastructure to understand what it does).

**Comment by dstillman** [comment]
Should be fixed in connector version 5.0.2, available now.

**Comment by fbennett** [comment]
Thanks! Works beautifully.
