### ISSUE TITLE
Fails to save proxied pdf behind projectEuclid

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-connectors#136]
Report: https://forums.zotero.org/discussion/66018/save-to-zotero-pdf-is-failing-without-error-message
See: http://projecteuclid.org/euclid.aoms/1177729694

**Comment by gustavdelius** [comment]
I should add that this is not specific to projectEuclid but appears to apply to all proxied pdf. They all fail without error message. I just submitted a debug report from a pdf from ScienceDirect, debug ID D1587881856

**Comment by gustavdelius** [comment]
It just occurs to me that perhaps this issue should be split into two, one for the failure of saving the pdf and another for the failure of the connector to check whether the save has happened and to issue an error message. Perhaps the second issue is more of a feature request?

**Comment by adomasven** [comment]
ScienceDirect works fine for me. Either way, let's continue the troubleshooting/feature discussion on Zotero forums. We use the github tracker for development conversations.

**Comment by adomasven** [comment]
Closing due to lack of follow up.
