### ISSUE TITLE
Allow requests from localhost

### ISSUE THREAD

**Issue by AndrewIsh** [zotero/zotero-connectors#139]
Initially discussed here: https://github.com/zotero/translation-server/issues/48

Currently requests have to have to match the following regex:
`/[\r\n]Host: *127\.0\.0\.1(:[0-9]+)?[\r\n]/i`
Because of this, I have been having problems sending requests that contain the Host header `localhost`. Would it be possible to modify the regex, thus:
`[\r\n]Host: *(127\.0\.0\.1|localhost)(:[0-9]+)?[\r\n]`

The reason for the Host check is to mitigate DNS rebinding attacks. AFAIK, allowing `localhost` shouldn't weaken this check.

**Comment by dstillman** [comment]
@AndrewIsh: Can you create this in https://github.com/zotero/zotero instead? Thanks.
