### ISSUE TITLE
Fix testTranslators.html

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#144]
Trying in Chrome:

> typeSchemaData.js Failed to load resource: net::ERR_FILE_NOT_FOUND

And once fixed, maybe we should bundle this all the time, with a pref to turn the button on, since you <a href="https://groups.google.com/d/topic/zotero-dev/JATd42gtca4/discussion">used to be able to load it in Zotero for Firefox</a> at a given URL.

**Comment by adomasven** [comment]
> And once fixed, maybe we should bundle this all the time, with a pref to turn the button on

There was a technical reason why it didn't used to be bundled all the time, related to having to do a bunch of extra work for every URL change, but probably possible to speed up.

**Comment by adomasven** [comment]
Closed with #144

**Comment by zuphilip** [comment]
(@adomasven You mean "Closed by # 143" otherwise the message is cyclic:)
