### ISSUE TITLE
Show different icon when viewing PDFs

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#150]
Not sure what, but I think it will help convey that you can save PDFs directly.

We're already showing "(PDF)" in the tooltip.

**Comment by adomasven** [comment]
Use the icon from the client? That'll be consistent with what it will look like there

**Comment by dstillman** [comment]
That one's low-res, so we should use a better one anyway (and replace the client one). The [official icon](http://www.adobe.com/legal/permissions/icons-web-logos.html) seems fine:

<img width="116" alt="pdf" src="https://user-images.githubusercontent.com/783082/28452230-a3351d8a-6dbf-11e7-9879-61bb7a44b31b.png">

**Comment by dstillman** [comment]
(It seems slightly weird to just show the official PDF icon with no indication that this is to save to Zotero, but it's consistent with what we're doing with all other icons, even if those are more closely associated with our own software.)
