### ISSUE TITLE
Show PDF icon for page with PDF iframe and no translator

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#155]
https://github.com/zotero/zotero-connectors/issues/152#issuecomment-318569335

**Comment by dstillman** [comment]
(If there are multiple we can save the first one, but that will almost never happen.)

**Comment by dstillman** [comment]
The downside, I guess, is that we would have to run a `document.querySelector('iframe')` call on every page without a translator, but hopefully that would be very fast.

**Comment by dstillman** [comment]
The implementation in c3793436875830d083794438941105daeb39aa50 seems way more complicated than I was thinking — I was assuming we would just look for an iframe with a URL with a path (not counting query string) that ended in `.pdf` and hope for the best.

But it also doesn't seem to be working for me. E.g., I'm not seeing a PDF icon on either https://www.cs.tut.fi/~jkorpela/html/iframe-pdf.html or https://pdfobject.com/static.html.

The latter page also shows a couple other techniques (`object` and `embed`) that can be used for PDF embedding, both using `type="application/pdf"`, that I imagine we could easily look for with `querySelector` from the main page.

**Comment by adomasven** [comment]
Both pages work for me on Chrome, Firefox and Safari.

**Comment by dstillman** [comment]
Working for me now. I guess maybe I was testing with Zotero closed? To support that I guess we'd have start sending URLs and cookies up to the API (and hoping sites don't have same-IP restrictions on cookies)?

**Comment by adomasven** [comment]
Detection works fine with Zotero closed. We don't support saving standalone PDFs to server now regardless of whether they are in a frame or not.

**Comment by dstillman** [comment]
PDF detection does not work for me in either Chrome or Firefox with Zotero closed. (It works if I just close Zotero while it's already showing a PDF icon and reload, but not if I close the tab and reopen it.)

**Comment by dstillman** [comment]
Well, now it is, with the latest commits. It wasn't previously.

**Comment by adomasven** [comment]
> Detection works fine with Zotero closed.

Ok, so it actually doesn't, but it doesn't really matter, because PDF saving to zotero.org doesn't either. We will revisit this once PDF saving to zotero.org is available.
