### ISSUE TITLE
Cookie handling problem on ScienceDirect in Safari

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#157]
With translator from https://github.com/zotero/translators/pull/1381 (if it's not yet merged), PDF saving fails for me in Safari on http://www.sciencedirect.com/science/article/pii/S0006349512000835 when proxied. PDF URL redirects to proxy login page in the client but is valid when loaded in Safari.

**Comment by adomasven** [comment]
Actually the issue is better suited for zotero/zotero.

Duplicate of zotero/zotero#1274
