### ISSUE TITLE
5.0.12 and dom.storage.enabled=false in Firefox

### ISSUE THREAD

**Issue by stupidus89** [zotero/zotero-connectors#160]
First of all, I don't know if the connector is supposed to be usable with `dom.storage.enabled=false`. But anyhow, I tested both cases with the new version:

With `dom.storage.enabled=false`:
In preferences the connector reports that zotero standalone is not available, even though it is running and I can access http://127.0.0.1:23119/connector/ping. When trying to use the connector on sciencedirect, nothing happens.

With `dom.storage.enabled=true`:
In preferences, the connector reports, that zotero standalone is available. However, when I try to use it on sciencedirect, a dialog appears informing me that zotero is not available. 

Firefox 54.0.1 on 64bit Arch Linux
Zotero 5.0.7
zotero connector 5.0.12

EDIT: I realized, that when I click on `enable saving in online library` in that dialog, it will actually save the item in zotero. Before, I had only tried to click on retry and cancel. However, it does not automatically add the pdf to zotero.

**Comment by dstillman** [comment]
You can revert to 5.0.11 from the [download page](https://www.zotero.org/download) — we're looking into problems with 5.0.12 in Firefox. Thanks.

**Comment by stupidus89** [comment]
Thank you, but 5.0.11 was not working for me either, because of the `dom.storage.enabled=false` setting. I was hoping, that 5.0.12 would fix that. However, I think now that 5.0.12 is actually working, if `dom.storage.enabled=true`. There is just this confusing message, that zotero is offline. However, if you click on `Enable saving in online library` once, it starts working and it is still working after a restart of firefox. At least, I have not seen that dialog again.

However, that "zotero is offline" dialog seems to be very confusing, because that online library thing sounds like it is related to the whole sync/cloud feature which I am not using.

**Comment by dstillman** [comment]
Try 5.0.13, available now.

**Comment by stupidus89** [comment]
5.0.13 works just as well as 5.0.12. To be sure, I unistalled the zotero connector and reinstalled it. The first time, I clicked on the zotero icon then, it shows this general welcome message. After that it works, and it does not show weird dialogs anymore.

However, attaching the PDF from sciencedirect is still not working. But I guess that is a different issue.

Of course, all of the above requires `dom.storage.enabled=true`. Is there any chance, that the zotero connector will ever work with `dom.storage.enabled=false`?

**Comment by dstillman** [comment]
Before 5.0.12, the connector stored data in localStorage. Now it uses the storage.local API available to WebExtensions. If `dom.storage.enabled=false` disables that, there's nothing we can do about that — the connector needs to be able to store data. But it would also seem like plausibly a Firefox bug if that setting affected extensions.

**Comment by stupidus89** [comment]
Thanks, I actually found a workaround. Setting `dom.storage.enabled=true`, but setting `dom.storage.default_quota=0` should have the same implications for privacy, i.e. disabling localStorage for websites, while the connector still works.

**Comment by dstillman** [comment]
OK, good to know — thanks.

**Comment by dstillman** [comment]
We've fixed this in version 5.0.17 of the connector — it should now be possible to use the connector with dom.storage.enabled=false.
