### ISSUE TITLE
Transition away from chrome. to browser. APIs

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-connectors#164]
Browser APIs are cleaner with Promises instead of callbacks and we can avoid [trashing the browser console](https://forums.zotero.org/discussion/67010/zotero-5-firefox-connector-show-a-lot-of-error-in-browser-console)

**Comment by gagarine** [comment]
This should help https://github.com/mozilla/webextension-polyfill

**Comment by lychichem** [comment]
@adomasven Now the issue happens again on Zotero Connector for edge downloaded from https://microsoftedge.microsoft.com/addons/detail/nmhdhpibnnopknkmonacoephklnflpho. Edge extensions use `extension://` scheme but Zotero connector uses `chrome-extension://` scheme to load browser-polyfill.js. Could you please fix it once again for Edge?

**Comment by adomasven** [comment]
@lychichem This github ticket is not relevant to the problem you are experiencing. Either way, please post all bug reports to [Zotero forums](forums.zotero.org), where we can have a proper conversation about the issue and go through any necessary troubleshooting steps.
