### ISSUE TITLE
Translators not updating properly

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#167]
OK, so finally have confirmation that something is causing translator retrieval not to work:

https://forums.zotero.org/discussion/comment/283853/#Comment_283853

We should figure out why this happens, but in the meantime maybe we should add some sort of hacky sanity check where we automatically re-fetch translators from the client if there are fewer than 490 or something. Not sure exactly when to do that check.

**Comment by adomasven** [comment]
Closed in 1af9f5d
