### ISSUE TITLE
Fix port-based EZProxy support

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#171]
This broke in the transition to the connector, but we don't have a port-based proxy to test it on. It's possible we can use the [trial version from OCLC](https://www.oclc.org/en/ezproxy/ordering.html#download) to at least get this working again and write some tests.

**Comment by dstillman** [comment]
Though https://twitter.com/robinshistory/status/900518824050651137 suggests this actually works, so, unclear…

**Comment by adomasven** [comment]
I don't think we'll be doing this. We don't have access to port-based EZProxy, it would be foolish to seek it just for this, especially given that it's clearly being phased out and rarely mentioned in the forums.
