### ISSUE TITLE
Repeated errors during translator save attempt

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#173]
Saving [this URL](https://www.amazon.com/Uncertain-Times-Anthropological-Approaches-Neoliberal/dp/1607326655/ref=sr_1_1?ie=UTF8&qid=1503678855&sr=8-1&keywords=uncertain+times+anthropological) with 5.0.18 never completes in Firefox, for whatever reason. (This appears to be fixed in the xhr-processDocuments branch.) With the code added since then (tested in https://github.com/zotero/zotero-connectors/commit/16a5f352fecfb05a24ecee5c5d2ca2f7f86128f3), trying to save that page produces hundreds of rapidly repeating errors like these in the console:

> TypeError: me is null translate.js:1277:6
> TypeError: null has no properties translate.js:1277:6

And makes Firefox unusable until it's restarted.

(We can work to merge xhr-processDocuments, but it seems like this might indicate a larger problem with the new code.)

**Comment by adomasven** [comment]
Fixed with https://github.com/zotero/zotero-connectors/commit/f89846b8e51066f1754db142d4b2acc62713f73d
