### ISSUE TITLE
[chrome] cannot save items to zotero from scholar.google.com

### ISSUE THREAD

**Issue by m4sub** [zotero/zotero-connectors#174]
It was always report an error when I tried to save an item to zotero from scholar.google.com. The problem happens in both MAC and Windows, and it only happens when I used on google (other platforms have no problem, such as IEEE, ACM, etc.). So maybe it is because google have updated their html code in recent days. Can anyone fix this problem?

**Comment by adomasven** [comment]
Please report problems on [Zotero Forums](https://forums.zotero.org/). The github issue tracker is for development discussions only. Also see the [reporting problems](https://www.zotero.org/support/reporting_problems) guide for more details.
