### ISSUE TITLE
Save hanging in Safari connector 5.0.20

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#177]
http://www.worldcat.org/title/law-of-the-sea-unclos-as-a-living-treaty/oclc/960766895&referer=brief_results

I'm getting this and then nothing else:

```
[Log] (3)(+0006370): HTTP POST http://127.0.0.1:23119/connector/getSelectedCollection (debug.js, line 171)
[Log] (3)(+0000009): Connector: Method getSelectedCollection succeeded (debug.js, line 171)
```

It works in Chrome.

**Comment by adomasven** [comment]
Assuming 5.0.20 is the latest commit, I cannot reproduce.

**Comment by dstillman** [comment]
Try in 5.0.20. I'm still seeing this, with 5.0.20, Safari 10.1.2, and Zotero 5.0.17.

**Comment by dstillman** [comment]
This mysteriously went away after reloading the extension. Translation-loading problem?
