### ISSUE TITLE
Save shortcut in Safari

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#180]
Not ideal, but we <a href="http://antrikshy.com/blog/safari-extension-development-keyboard-shortcuts">could do it</a> by listening for the shortcut in an injected script.

Requested: https://forums.zotero.org/discussion/67618/keyboard-shortcut-key-combo-hotkey-for-saving-reference-in-safari-extension

**Comment by adomasven** [comment]
Duplicate of https://github.com/zotero/zotero-connectors/issues/60
