### ISSUE TITLE
RIS/BibTeX interception to read-only view behaves differently from save button

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#185]
https://forums.zotero.org/discussion/comment/287032/#Comment_287032

Importing to "Duplicate Items"/"Unfiled Items" in My Library throws an error in the client, but the save button saves to the library. Importing to a read-only library root saves to My Library, but the save button shows the read-only error in the connector.

We should probably fix part of this in the client too, but on the connector side we should handle this the same way as the save button.

**Comment by adomasven** [comment]
> Importing to "Duplicate Items"/"Unfiled Items" in My Library throws an error in the client, but the save button saves to the library.

I'm not seeing this. Saves to My Library without errors both ways.

> Importing to a read-only library root saves to My Library, but the save button shows the read-only error in the connector.

So return 400 from the client for import and display the message in the progress window to switch libraries is what I'd say for this.

**Comment by dstillman** [comment]
> I'm not seeing this. Saves to My Library without errors both ways.

Yeah, I already fixed the import error in the client when something other than a collections was selected.

In https://github.com/zotero/zotero/commit/48d4d2d5a5f26c92345406c5a7e23d64659252d8 I've standardized the connector server behavior to return `500` in all cases. (Well, almost all cases. Is `savePage` actually still used for anything?)

The connector needs to be updated to handle this for the `/import` request, and the `selectItems` handling is a little weird too. I'll leave those for you.

**Comment by adomasven** [comment]
> (Well, almost all cases. Is savePage actually still used for anything?)

If there exist translators that don't run on Chrome, but run on Standalone, then yes. We should probably have a conversation about browser support and relevant flags with the translator folk
