### ISSUE TITLE
RIS/BibTeX interception doesn't work if link opens new tab

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#188]
1) Go to http://www.worldcat.org/title/test/oclc/798059672&referer=brief_results
2) Click on Cite/Export
3) Click "Export to EndNote / Reference Manager"

A new tab opens, and even though the file is served with the correct Content-Type, our interception doesn't work. (At least, I think that's the reason — I didn't find the function it's calling to see exactly what it's doing.)

The save button can be used on WorldCat, obviously, but it'd be nice for this to work in general.

**Comment by adomasven** [comment]
We can't display a prompt about import in a new tab, because there's not a valid webpage to inject the UI into. Thoughts?

**Comment by adomasven** [comment]
Although this is just broken for me with the current version. It intercepts the request and does nothing with it, failing to inject the scripts. So we can fix that, but otherwise this is problematic.

**Comment by dstillman** [comment]
What is https://github.com/zotero/zotero-connectors/commit/0cd352e4fbc2a87242a5598def14f310d4da633f supposed to do? Now if I click the WorldCat RIS link in Chrome, I just get an empty tab.

**Comment by adomasven** [comment]
Ok. I re-addressed this in 2e0cb2cb2033ea47095ad2f06e1287d538086224.

**Comment by dstillman** [comment]
Still not working for me. In Chrome, it now opens and closes a new tab and then automatically launches the file via the OS (which tries to start a new copy of Zotero and gives the error that Zotero is already open, though that's a separate problem). Firefox opens a new tab and then gives me the open/save dialog for the file (which would result in the same behavior). So still not intercepting for me in either browser.

**Comment by adomasven** [comment]
As I wrote above

> We can't display a prompt about import in a new tab, because there's not a valid webpage to inject the UI into. Thoughts?

Since then I have thought of redirecting into a blank Zotero tab where we could display the prompt UI, although at the very least that way we will get trailing tabs if the users click cancel.

------

This now just performs the default download operation for the browser if there's no target to inject the UI into.

**Comment by dstillman** [comment]
> Since then I have thought of redirecting into a blank Zotero tab where we could display the prompt UI, although at the very least that way we will get trailing tabs if the users click cancel.

This seems good. A trailing tab on Cancel doesn't seem like a big deal. (Can we not close the tab after a half-second or something after retriggering the original file?)

And I guess my Chrome somehow ended up launching RIS files by default. I'll look into why launching a RIS file when Zotero is open now results in a new copy of Zotero opening.

**Comment by adomasven** [comment]
> And I guess my Chrome somehow ended up launching RIS files by default. I'll look into why launching a RIS file when Zotero is open now results in a new copy of Zotero opening.

http://www.presentermedia.com/blog/2013/10/my-file-automatically-opens-instead-of-saving-with-chrome/

**Comment by dstillman** [comment]
Launching issue: https://github.com/zotero/zotero/issues/1330

**Comment by dstillman** [comment]
Crazy things still happening for me in Firefox. I'm getting constant reloading and pinging in the new tab, and a mostly unresponsive Firefox until I close the pane. Tested with Fx 56.

**Comment by dstillman** [comment]
Working now, though the tab is staying open in Firefox with "Scripts may not close windows that were not opened by script." in the console, but maybe nothing we can do about that.
