### ISSUE TITLE
Add snapshot option to context menu in Chrome when viewing PDF

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#19]
https://forums.zotero.org/discussion/35327/zotero-in-google-chrome/

It looks like Chrome's own menu is still displayed when viewing a PDF, and I still have a menu option there from another extension. We should see if we can add the save option there.

**Comment by maxsu** [comment]
I second this, going to look into working this out. Being able to directly save PDFs would be a great speedup.

**Comment by dstillman** [comment]
So in theory this should be possible by changing the context menu item's [ContextType](https://developer.chrome.com/extensions/contextMenus#type-ContextType), but the only way I can get the menu item to appear on PDFs is by using "all", which we don't want to do, since it would enable the option for links, embedded images, etc. The documentation says "all" is equivalent to all the others combined, but that's seemingly not the case.

Anyhow, we now have a persistent toolbar button that can be used to save PDFs, so this doesn't really matter. If ContextType for PDFs is fixed in Chrome, we can revisit.

**Comment by adomasven** [comment]
Since we are controlling for PDF context ourselves (with `Content-Type: "application/pdf"` check), we can change the context to "all" in `_showPDFContextMenuItem` and display the menu (as how it was intended in the existing code, by the looks of it).
