### ISSUE TITLE
Translator problems on Amazon search results page

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#191]
With the current master in Firefox 56, I don't get a folder icon on this page:

https://www.amazon.com.br/s/ref=nb_sb_noss/144-2745992-3387436?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias=aps&field-keywords=contrato+almedina

And I see this in the console:

> Error: Url changed mid-injection into 4-0 at moz-extension://691e00bc-7e7b-9c45-976f-72954b29ad85/background.js:320  zotero.js:224:4

In Firefox 57 Beta, I get the folder icon, but (possibly like the person in the [thread](https://forums.zotero.org/discussion/67886/zotero-5-0-saving-from-web-pages-fails) where this was reported, though that was with Fx 52) if I select the third result ("Deveres de Consideração…") and save, it hangs on the `doGet()` for WorldCat within `processDocuments()`. (This problem might go away with the `xhr-processDocuments` branch, so if we fix the detection problem first I can rebase that branch and see if this still happens.)

Works in Chrome.

**Comment by adomasven** [comment]
This is really rather problematic with firefox. I've filed a [ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1405603) with mozilla, we'll see what they say.

**Comment by adomasven** [comment]
Fixed with https://github.com/zotero/zotero-connectors/commit/f89846b8e51066f1754db142d4b2acc62713f73d
