### ISSUE TITLE
Somtimes references seem impossible to add

### ISSUE THREAD

**Issue by gagarine** [zotero/zotero-connectors#196]
On Firefox 57.0b10:
- go on a book on amazon
- click on the addon button to add the book to zotero
- the notification "Saving to ... " appear
- nothing append (notification stay).

The Debug ID is D787464222.

Zotero is launched.
Everything is up-to-date.

**Comment by gagarine** [comment]
Oh it seem to be a https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content problem.

I have stuff like that in the console:
Blocked loading mixed active content “http://static1.worldcat.org/wcpa/rel20171016/css/modals_jquery.css”

**Comment by adomasven** [comment]
I'm pretty sure this is fixed with https://github.com/zotero/zotero-connectors/commit/f89846b8e51066f1754db142d4b2acc62713f73d which hasn't been released yet.
