### ISSUE TITLE
Don't send translator error reports in private-browsing mode

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#199]
There's [existing code](https://github.com/zotero/zotero/blob/bbb6434524e9b4e8604cad5eb4ffbcbe9fe718a5/chrome/content/zotero/xpcom/translation/translate.js#L2212) to prevent this for Zotero for Firefox, but we should update that for the connector.

This is deep in the translation architecture, so the best way to do this is probably to include a flag in the object passed to `translate()` to indicate that a report shouldn't be sent on failure.

**Comment by adomasven** [comment]
> This is deep in the translation architecture, so the best way to do this is probably to include a flag in the object passed to translate() to indicate that a report shouldn't be sent on failure.

There's already a [pref](https://github.com/zotero/zotero/blob/bbb6434524e9b4e8604cad5eb4ffbcbe9fe718a5/chrome/content/zotero/xpcom/translation/translate.js#L2202-L2206) controlling this though and at least for the client that's the only way of control. Thoughts on handling this?

**Comment by dstillman** [comment]
That pref isn't really relevant. This is specific to private browsing, and is just a reimplementation of the existing protection we've always had in Zotero for Firefox. Extensions shouldn't upload URLs from private browsing with default settings.

What do you mean by "at least for the client that's the only way of control"? This is just for the connector.

**Comment by adomasven** [comment]
This is a question regarding adding a flag to be passed to `translate()`. So we'd have `translate.reportTranslationFailures` flag that had been passed in via `translate()` and the pref, which is confusing. I propose to just add the incognito check there in translate.js.

**Comment by dstillman** [comment]
Ah, I see what you mean. I was assuming we might not have easy access to the incognito check at the point of the existing code. If we do, that's fine. If not, I figured we could have a `skipFailureReporting` or something at the point of the `translate()` call, and that would disable reporting even if the pref was on.

**Comment by adomasven** [comment]
Closed with 0192bdac56b7125b1eddc9bd7af33bb4ce3436c5
