### ISSUE TITLE
Automatically fall back to other translators on save failure

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#200]
Similar to https://github.com/zotero/translation-server/issues/51, we should always save data, even if it's just generic webpage data. People shouldn't need to manually try other translators in the list (and most people likely don't know there's a context-menu option anyway). We should still show an error that a translator failed, with one or more " — falling back to COinS" messages, and we should still report the translator failures.

If DOI is in the list, the select items dialog could pop up unexpectedly, but there's a good chance that the main item will be in that list, so it's worth it. Relatedly, the updated Embedded Metadata translator can handle some of this more gracefully internally after https://github.com/zotero/translators/issues/1092, but the connector itself should do it now with all available translators.

(We really should've done this 10 years ago, or at least a couple years ago when we combined the translator and webpage buttons…)

**Comment by adomasven** [comment]
Closed with 3d4616490f83c909e26ea4722f7585940f1cc69d

Looks like this 
![screenshot from 2017-11-10 10-00-36](https://user-images.githubusercontent.com/5899315/32658451-bdfaa444-c622-11e7-887a-1f3fa0c544e2.png)
