### ISSUE TITLE
Custom attachment server when saving to zotero.org

### ISSUE THREAD

**Issue by petronny** [zotero/zotero-connectors#201]
Hi,
I want to use zotero more remotely which means using the browser plugin without the zotero application.
So I set up to save items to zotero.org.
But this will upload the attachments to zotero.org too.
Is it possible to let zotero connector upload attachments to my custom WebDAV server, just like the zotero application?

PS. I'm using chrome and my OS is linux.

**Comment by dstillman** [comment]
No, sorry — you have to save to the Zotero client to use WebDAV.

(Please post support questions to the Zotero Forums.)
