### ISSUE TITLE
Fix failure on invalid proxy entry

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#211]
https://forums.zotero.org/discussion/comment/295210/#Comment_295210

Add a `try`/`catch` to `_getProxiesForURL()` to make sure it never breaks things, and ideally figure out how this person ended up with a proxy entry without a scheme in the first place. Should probably also figure out a good place to correct bad entries that exist.

**Comment by adomasven** [comment]
We [validate](https://github.com/adomasven/zotero-connectors/blob/28089b86ceec320e7b97b26d1211b2d66fa4bff2/src/common/proxy.js#L451-L480) proxies before usual saving, but weren't for client imports. We will now for both.
