### ISSUE TITLE
Proxies getting deleted

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#214]
A proxy entry was deleted when I clicked Don't Proxy This Site, and when I went to check the proxy it was gone, with this error:

> [JavaScript Error: "Invalid proxy http://%h.mutex.gmu.edu/%p: TypeError: Cannot read property '1' of null"]

I reproduced this by creating an entry for `http://%d.mutex.gmu.edu/%p` with entries for jstor.org and sciencedirect.com and then loading jstor.org.

**Comment by dstillman** [comment]
(I'm not sure if proxy entries are now supposed to include the scheme. If not, my existing entry hadn't been converted to remove the `http://`.)

**Comment by adomasven** [comment]
The [migration](https://github.com/zotero/zotero-connectors/blob/master/src/common/zotero.js#L100-L135) occurs based on version number
