### ISSUE TITLE
Translators doesn't work on some websites when using newer version of connectors

### ISSUE THREAD

**Issue by htimer** [zotero/zotero-connectors#215]
Pages of articles on geoscienceworld.org can't be correctly translated and can be saved as webpage when using newer version of zotero-connector for both firefox and chrome. But they can both work well on most of other sites.

Here's what I got from firefox -> zotero-connector -> preference -> advanced -> report error:

Report id: 1536924076
```
[JavaScript Error: "Frame not found, or missing host permission" {file: "undefined"}]

[JavaScript Error: "Inject: Timed out 0 - https://pubs.geoscienceworld.org/ssa/srl/article-abstract/87/4/930/314131 after undefined
Zotero.Connector_Browser</this.injectScripts/timeout<@moz-extension://22082bfa-fc89-4392-bf16-def88ec10d3e/background.js:334:20
"]
```

Tested versions are:
* firefox
5.0.22: good
5.0.25: bad
5.0.31: bad
* chrome
5.0.25: good
5.0.31: bad

**Comment by adomasven** [comment]
Please use the [Zotero Forums](https://forums.zotero.org/) for translation errors reports. This tracker is for developer use only
