### ISSUE TITLE
Translator working withing Scaffold and not in browsers?

### ISSUE THREAD

**Issue by symac** [zotero/zotero-connectors#216]
Hello,
last month, I [posted on zotero-dev](https://groups.google.com/forum/#!topic/zotero-dev/Kp54deoZy5I) regarding an issue with Zotero connector not offering the correct translator in Firefox. The only answer I had off-list was that it might be related to some troubles with the connector that should be fixed with the new versions. Since that time there has been new versions and I still get the issue.

How to reproduce : 
- navigate to http://www.sudoc.abes.fr/DB=2.1/SRCH?IKT=12&TRM=162345658
- try to save the page to Zotero, the only available options are "Save webpage with Snapshot", "Save webpage without Snapshot".
- open http://www.sudoc.abes.fr/DB=2.1/SRCH?IKT=12&TRM=162345658 from Scaffold > Browser, try to load translators, the first one under "Matching translators" is "Library Catalog (PICA)", run detectweb returns Thesis, which means we should see the thesis icon in browser. This was the case some weeks/months ago, not the case anymore.

As it was working fine previously and is still working fine within Scaffold, I suspect the issue is not related to the translator (which still works on website using the same ILS) but rather to the connector. Therefore I am posting there rather than on Zotero forums.

**Comment by adomasven** [comment]
Sorry it took a while to respond. This is still something to be reported on the forums. Please create a new thread there, since it seems from your zotero-dev posts that you had multiple issues.

**Comment by symac** [comment]
Thanks @adomasven, I [just report it to the forum](https://forums.zotero.org/discussion/69821). If you have any idea about what could be wrong don't hesitate to comment there. The post I have created is about the main issue which I really suspect has something to do with the connector :)
