### ISSUE TITLE
Target Selector issues

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#220]
- [x] Allow library changes
- [x] Show libraries and recent collections in top drop-down
- [x] Don't auto-expand collections
- [x] Handle edge cases during updates
  - [x] If item has become a child item (Retrieve PDF Metadata), move the parent instead (and ideally update the line in the popup, but that's for later)
  - [x] If item is in trash, update but don't focus trash
  - [x] If item was deleted…skip?
- [x] Instead of saving again on button click, show the existing progress window and allow changes (except when choosing a different translator or on a `multiple` page)
- [x] Handle SESSION_NOT_FOUND after Zotero restart, somehow
- [x] Maybe don't prevent main-page scrolling when over the collapsed progress window
- [x] Try to find a better, non-jittery way to prevent scrolling the main page at the bottom of the tree [seems OK now]
- [x] Fix annoying expand/collapse behavior when clicking on a tree row (why, Mozilla?)
- [x] Fix collapsed tree if My Library has focus (caused by the previous issue, because we simulate a click on the tree to give it keyboard focus)
- [x] Fix script loading in progressWindow.html in Safari (relative paths)
- [x] Maybe get rid of Webpack dependency by using external CSS/SVG in tree.js
- [x] Fix on non-translator pages

**Comment by adomasven** [comment]
> Handle SESSION_NOT_FOUND after Zotero restart, somehow

Disable changes for open progress windows with SSE when Zotero leaves.
