### ISSUE TITLE
No images on medium.com

### ISSUE THREAD

**Issue by XelionIO** [zotero/zotero-connectors#222]
When trying to save a medium.com article on Zotero using the Zotero Connector, i've noticed that the snapshot doesn't have pictures. After inspection, it appears that the medium.com website only load the pictures once the pictures are on the readable part the screen.

One solution may be to use a user agent changer to load the mobile version who preload the pictures but the Zotero connectors doesn't allow that. Another solution may be to save an html file from the browser once the pictures are loaded, then load that preloaded html file into the browser. Then use the Zotero connectors but it can't save from a file:// url.

**Comment by adomasven** [comment]
This might be addressed with #194 

Either way, this tracker is for developer use only. Please post feature requests to [Zotero forums](https://forums.zotero.org/)
