### ISSUE TITLE
Support <link> rel="alternate" and/or rel="meta"

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#223]
https://forums.zotero.org/discussion/comment/301964/#Comment_301964

(Though there are some tricky implementation questions, as noted there.

**Comment by adomasven** [comment]
> It seems like we want to prioritize any priority=100 web translator, but it gets messy after that. RIS is 100 and Embedded Metadata is 320. Do we want a linked RIS to take precedence over embedded metadata?

I think this should be done in translators, perhaps the generic translator, once we have such a thing and once it can return [multiple save options](https://github.com/zotero/translators/issues/1092#issuecomment-333299735). We already have a few generic translators that perform page-scans, like the DOI translator. Why would we want to do this in the Connector?

**Comment by dstillman** [comment]
Sorry, wrong repo. Also, dupe of https://github.com/zotero/translators/issues/77.
