### ISSUE TITLE
Throwing "NS_ERROR_FAILURE" on ResearchGate (related to browser history API)

### ISSUE THREAD

**Issue by Rendez** [zotero/zotero-connectors#224]
The Zotero extension is throwing a pretty bad exception (`NS_ERROR_FAILURE`) when saving any page to "My Library" using the extension in Chrome and Firefox.

The stack trace led us to think it's related to the browser history API. At ResearchGate we're using this [history.js](https://github.com/ReactTraining/history) library, and somewhere inside [this function call](https://github.com/ReactTraining/history/blob/master/modules/createBrowserHistory.js#L37) we receive `NS_ERROR_FAILURE` from our logs containing *Zotero* in the `userAgent` string.

Here's a couple of userAgents I've gathered in case the versioning there helps:

- `Mozilla/5.0 (Windows NT 6.3; WOW64; rv:52.0) Gecko/20100101 Zotero/5.0.35.1`
- `Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Zotero/5.0.25`

**Comment by adomasven** [comment]
We see some `NS_ERROR_FAILURES` from snapshot saves in our user submitted error reports, but they are generally ok to ignore, unless saving fails.

Either way, this is the wrong repo and the tracker is generally for developer use only. Please see [reporting guidelines](https://www.zotero.org/support/reporting_problems), report the issue on [Zotero forums](https://forums.zotero.org/) and we will create tickets as appropriate.
