### ISSUE TITLE
Target selector: Switching from one library collection to another behaviour is incorrect.

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-connectors#235]
I think what is happening is that `updateSession` only receives the collection ID as the target without the library ID. You wouldn't see this break unless you try to move from a collection ID from one library to the other where at least one of them is missing a given ID.

**Comment by dstillman** [comment]
What's not working? This seems to be working for me. A collectionID implies a libraryID

**Comment by adomasven** [comment]
```
TypeError: Zotero.Server.Connector[actionUC] is undefined

    TypeError: Zotero.Server.Connector[actionUC] is undefined
        Zotero.Server.Connector.SaveSession.prototype.update@chrome://zotero/content/xpcom/server_connector.js:177:9
    From previous event:
        Zotero.Server.DataListener.prototype._bodyData@chrome://zotero/content/xpcom/server.js:327:3
        Zotero.Server.DataListener.prototype._headerFinished@chrome://zotero/content/xpcom/server.js:299:3
        Zotero.Server.DataListener.prototype.onDataAvailable@chrome://zotero/content/xpcom/server.js:203:4
```

I can consistently reproduce this by selecting C3 in L1, then C13 in L2 and then C3 in L1 again.

**Comment by dstillman** [comment]
That's with current master? Not your GDocs branch?

**Comment by adomasven** [comment]
Current master

**Comment by dstillman** [comment]
OK, got it.
