### ISSUE TITLE
PDF stored in arXiv not downloaded from NASA/ADS

### ISSUE THREAD

**Issue by Gabriel-p** [zotero/zotero-connectors#24]
Often times a NASA/ADS link for an article will not have a PDF available for download but it will display a link to the article's arXiv page where the PDF _is_ available (e.g.: http://adsabs.harvard.edu/cgi-bin/bib_query?arXiv:0906.2173)

If one uses the Zotero connector for Chrome (haven't tried with any other) from the NASA/ADS site, the PDF will _not_ be saved. If the article is saved from its arXiv page, it will.

Couldn't the connector automatically check if the PDF is available in arXiv and store it even from the NASA/ADS site?

**Comment by adomasven** [comment]
No longer the case and wrong repo either way.
