### ISSUE TITLE
[Safari] Target Selector and Modal Prompt fail to display on forums.zotero.org

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-connectors#240]
1. In Safari navigate to https://forums.zotero.org/discussion/71243/available-for-beta-testing-zotero-connector-target-selector#latest
2. Click the save button
3. Console displays `[blocked] The page at about:blank was not allowed to display insecure content from safari-extension://org.zotero.zoteroconnectorforsafari-0000000000/2cc205a4/progressWindow/progressWindow.html.`

I am not sure what causes this. I've tested on the JSTOR page with both http and https protocols and it works there.

**Comment by dstillman** [comment]
I'm not seeing this in Safari 11.0.3.

**Comment by dstillman** [comment]
(But check whether you're still getting it after https://github.com/zotero/zotero-connectors/commit/8365b6271df08ee984c1b0292631ea608bfffa6d, even though I was getting a different error.)

**Comment by dstillman** [comment]
This is still working for me in 11.1.
