### ISSUE TITLE
Add URL and accessed-date into parent item description

### ISSUE THREAD

**Issue by Alex-Linhares** [zotero/zotero-connectors#242]
I am using the chrome extension, and if I try to add, say the following pdf to zotero:  

https://media.readthedocs.org/pdf/sdm-framework/stable/sdm-framework.pdf

It correctly copies the pdf file and gets some of its metadata into the parent item.  The parent item reference, however, does not include the URL or access-date of the pdf, which should be standard in citations of the parent item.

**Comment by adomasven** [comment]
Please post bug reports and requests on [Zotero forums](forums.zotero.org). This tracker is for developer use only
