### ISSUE TITLE
Modal prompt broken in Firefox

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#243]
https://forums.zotero.org/discussion/comment/306512/#Comment_306512

> result is undefined

From a bisect it looks like this broke in 314c86e500e7640d90b1e3797fee6287327f837b

**Comment by adomasven** [comment]
Closed with https://github.com/zotero/zotero-connectors/commit/97283ddd24afb2acf4404d8f032f0452fb999ffa
