### ISSUE TITLE
Bookmarklet fails when used with Standalone

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero-connectors#25]
From Chrome
`The page at 'https://www.zotero.org/bookmarklet/iframe.html' was loaded over HTTPS, but ran insecure content from 'http://127.0.0.1:23119/connector/getTranslators': this content should also be loaded over HTTPS.`

We can't communicate with Standalone over HTTPS at this point, but perhaps we could add or generate "on-the-fly" a self-signed certificate.

**Comment by simonster** [comment]
Fixed by zotero/zotero#594 and zotero/zotero@fa75beeefda4c9841e5d726061101908666041f0
