### ISSUE TITLE
Unstyled citation inserted in Google Docs under certain circumstances

### ISSUE THREAD

**Issue by stakats** [zotero/zotero-connectors#257]
Steps to reproduce:

1. Create a new footnote in a Google Doc
2. Add Zotero citation, set style to Chicago Full note
3. Select a journal article where the title field is empty

**Comment by adomasven** [comment]
(Issues regarding Google Docs integration are more appropriate at [zotero/google-docs-integration](https://github.com/zotero/zotero-google-docs-integration))
