### ISSUE TITLE
Bookmarklet: Save popup doesn't stay open during save-to-server login

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#259]
We can probably hack this by calling progressWindowIframe.mouseenter when the frame is opened and progressWindowIframe.mouseleave when it's closed.

**Comment by adomasven** [comment]
I can't seem to reproduce this. Which browser?

**Comment by dstillman** [comment]
Safari

**Comment by adomasven** [comment]
Closed in 62d3f2d24ccc1ec41384e16f168b425fd9157f22
