### ISSUE TITLE
Periodic refresh after automatic proxy redirection

### ISSUE THREAD

**Issue by retorquere** [zotero/zotero-connectors#266]
If I open a large number of tabs (as I usually do) and some of those tabs trigger the automatic proxy redirect, the session on the proxied page sometimes times out before I get to it and then the URL is lost (refreshing just gets me an error from the proxy). Would it be possible to have the proxied page be reloaded every minute or so to keep the session alive?

**Comment by dstillman** [comment]
I think this is out of scope for us, sorry. (Also, at least with the EZproxy proxy we have access to, if you get logged out for some reason, the proxied URL just gives you the login page and you can get right back to the article. I think that's pretty standard.)

**Comment by retorquere** [comment]
Doesn't work that way for the proxy I have access to. After the session expires, I do get a login page, but I don't get back to the article, I get an error.
