### ISSUE TITLE
Allow changing keyboard shortcuts

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-connectors#267]
A follow up from #60. A user reports the shortcut key interfering with Google Docs dictate shortcut and while browsers themselves would do good to provide an UI for customizing these, since they do not, we should consider it.

https://forums.zotero.org/discussion/74987/zotero-plugin-for-chrome-os-x-change-apple-s-keyboard-shortcut

**Comment by dstillman** [comment]
[Chrome allows this](https://forums.zotero.org/discussion/comment/322266/#Comment_322266), and there are almost certainly plans for Firefox to do the same, so we don't need to do this.
