### ISSUE TITLE
Bookmarklet not working locally on browsers with w3c secure-context implementation for localhost

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-connectors#268]
A follow up from https://github.com/zotero/zotero-connectors/issues/63#issuecomment-423969463.

The bookmarklet currently doesn't work locally with [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1376310) and [Safari](https://bugs.webkit.org/show_bug.cgi?id=171934).

Since the Firefox issue is a bug and not a choice by developers it's more likely to be resolved and someone recently posted about the workaround of using [ipv6 loopback address might work](https://bugzilla.mozilla.org/show_bug.cgi?id=1376310#c13):

> just discovered that opening an EventSource from a secure context to:
> 1) http://localhost:8080 -> fails
> 2) http://127.0.0.1:8080 -> fails
> 3) http://[::1]:8080 -> works!
> 
> So using the IPv6 localhost "[::1]" could be a workaround for this issue.

I've not tested this yet, but this is something to keep in mind.

**Comment by dstillman** [comment]
No more bookmarklet
