### ISSUE TITLE
Simplify copying a Debug ID

### ISSUE THREAD

**Issue by valioDOTch** [zotero/zotero-connectors#271]
I just compared the process for providing a Debug ID in Zotero VS the Zotero connector.

The desktop app provides a simple copy to clipboard button
![image](https://user-images.githubusercontent.com/800467/51080232-09857900-16d8-11e9-80a6-e02864369420.png)

In contrast the connector only provides a window.alert as far as I can tell
![image](https://user-images.githubusercontent.com/800467/51080241-2a4dce80-16d8-11e9-8b74-86a2c114ac72.png)
This poses the problem that the ID itself can't be copy-pasted (at least in Chrome, haven't checked for other browsers).

I haven't looked into the code yet, but as a front-end dev I'm aware, that you probably can't provide the copy-paste button functionality and you may have your reasons to rely on that simple implementation.
However you may provide an improved UX, if you'd simply change the alert into a window.prompt like

`window.prompt("Your debug output has been submitted. Please copy the text line below and provide it for reference","The Debug ID is D1612646623");`

This easily allows the user to copy the debug ID
![image](https://user-images.githubusercontent.com/800467/51080286-eb6c4880-16d8-11e9-887e-cdb21ec89bd6.png)

Of course there's a slight downside to this: the user may get confused by the two buttons. 
But if that's an argument I'd certainly would suggest a RFC for the desktop app dialog ;-)

btw: Besides, I'd like to submit a RFC for the wiki article to clarify this process for first-time users, but I'm not certain where I should do this..any hints?

**Comment by dstillman** [comment]
`prompt()` would definitely be too confusing, but we have an in-page modal dialog that we could use for this. @adomasven would know better how easily we could use that in the preferences at the moment.
