### ISSUE TITLE
Take a snapshot of every webpage

### ISSUE THREAD

**Issue by dpffxhad** [zotero/zotero-connectors#272]
I'd like to have a snapshot of every webpage I visit.
Is it possible to have some sort of setting to enable snapshotting every webpage I visit without me having to click on extension for every page I visit?

**Comment by dstillman** [comment]
Please post feature requests to the Zotero Forums.

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

I don't see us offering this feature, which, due to how snapshots work, would be extremely resource intensive.
