### ISSUE TITLE
Consider GDocs export option to transform citations to inline links, pointing to bibliography

### ISSUE THREAD

**Issue by valioDOTch** [zotero/zotero-connectors#273]
When exporting a document from Google Docs, Zotero warns us that the citations will point to zotero.org
![image](https://user-images.githubusercontent.com/800467/51663206-704b4200-1fb6-11e9-8a84-5766a74b9fb0.png)

A cool feature would be to have an option that allows to convert those citations to inline links to the bibliography, so that it would work similar to inline links to chapters in Google Docs or the references in Wikipedia.
![wikipedia-references-ixd](https://user-images.githubusercontent.com/800467/51663584-6d048600-1fb7-11e9-890b-ed73a3f9d4c4.gif)

The sample document for this feature request ticket can be found here
https://docs.google.com/document/d/1IxybxgJcFRMohEjg4ApXLpUPd7M8-LTtvtpFs24k0UI/edit#

**Comment by valioDOTch** [comment]
I just realized that I should post feature requests to the Zotero forums instead. 
Sorry, about that.
I will do that in the future and close this ticket now.

**Comment by adomasven** [comment]
This is also being requested for Word and LibreOffice on the forums and the current response is that we generally want this, but it is rather complicated to achieve and so not happening in any near future.
