### ISSUE TITLE
Link to Site Access Limits page for errors on some sites

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#279]
We should link to <a href="https://www.zotero.org/support/kb/site_access_limits">Site Access Limits</a> at least on Google Scholar. (Ideally we would throw a specific error from the 403 we get there, but I'm not sure the translator architecture is set up to do that.)

**Comment by dstillman** [comment]
Same for PubMed: https://forums.zotero.org/discussion/86996/save-to-zotero-pubmed-problem

**Comment by adomasven** [comment]
I read the full discussion on PubMed and that seems to be something else, so I didn't include it in the commit, but the list is easily modifiable if needed.
