### ISSUE TITLE
Chrome shortcut can not be changed/stopped

### ISSUE THREAD

**Issue by Honghe** [zotero/zotero-connectors#283]
Environment:
- Ubuntu 16.04
- Chrome Version 74.0.3729.131 (Official Build) unknown (64-bit)
- Zotero Connector 5.0.56

![image](https://user-images.githubusercontent.com/1092722/57688457-0d1e1200-7670-11e9-815e-2af24306bf53.png)

**Comment by dstillman** [comment]
Please post support requests to the [Zotero Forums](https://forums.zotero.org). See [How Zotero Support Works](https://www.zotero.org/support/zotero_support) for more info.

(But the Zotero Connector defines a standard Chrome extension shortcut, and what you can do with it is up to Chrome.)
