### ISSUE TITLE
Auto Proxy doesn't redirect

### ISSUE THREAD

**Issue by vinc96** [zotero/zotero-connectors#285]
Zotero connector's auto proxy doesn't work recently. It doesn't redirect any pages which it can redirect in the past.

To reproduce this issue:
1. install Zotero Connector
2. make Zotero Connector recognize a university proxy, e.g. [UofU](http://lib.utah.edu/help/off-campus.php). Zotero Connector will prompt the following
> Zotero detected that you are accessing lib.utah.edu.ezproxy.lib.utah.edu through a proxy. Would you like to automatically redirect future requests to lib.utah.edu.ezproxy.lib.utah.edu through %h/%p?    [Accept] [Proxy Settings]
3. Accept, and go to an IEEE page, e.g. [paper](https://ieeexplore.ieee.org/document/8645427)

Redirection doesn't take place after operation 1,2,3. Instead, simultaneously, the following error log is generated in Zotero Connector's options page -> Report Errors
> [JavaScript Error: "Invalid proxy %h/%p: TypeError: Cannot read property '1' of null"]

> [JavaScript Error: "Cannot access contents of url "chrome-search://most-visited/single.html?title=Most%20visited&removeTooltip=Don%27t%20show%20on%20this%20page&enableCustomLinks=1&addLink=Add%20shortcut&addLinkTooltip=Add%20shortcut&editLinkTooltip=Edit%20shortcut". Extension manifest must request permission to access this host."]

Thanks

**Comment by dstillman** [comment]
It certainly still works in general. If it's not working for you, post to the [Zotero Forums](https://forums.zotero.org), and include a <a href="https://www.zotero.org/support/debug_output#debug_output_logging">Debug ID</a> from the Zotero Connector for logging into the proxy and getting the above message (with `requests to lib.utah.edu.ezproxy.lib.utah.edu through %h/%p?`).

**Comment by vinc96** [comment]
I see, thanks
