### ISSUE TITLE
Same-domain HTTPS XHR requests that redirect to HTTP URLs fail

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#293]
https://forums.zotero.org/discussion/79135/error-when-saving-from-nature-website

This one is complicated.

> Mixed Content: The page at 'https://www.nature.com/articles/s41567-019-0603-8' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://citation-needed.springer.com/v2/references/10.1038/s41567-019-0603-8?format=refman&flavour=citation'. This request has been blocked; the content must be served over HTTPS.

The HTTPS RIS URL redirects to an HTTP URL (even though the destination server does support HTTPS). This fails as mixed-content 1) in Chrome, when using non-background XHR (as we're doing now) and 2) in Firefox, when using content XHR, which we're doing [to fix an issue with Referer](https://github.com/zotero/zotero-connectors/blob/fbe13c6881fa14b44db2a86efbed542aa706e52c/src/common/http.js#L80-L86). It works in Firefox if privileged non-background XHR is used.

The proper fix here would be for Nature to fix its site to use HTTPS. It's possible we can just contact them and get them to redirect to that instead.

The weird fix would be to force HTTPS for that particular domain (`citation-needed.springer.com`), which isn't particularly our business but would protect users' privacy when downloading from Nature.

The normal fix would be to switch to background HTTP ("COHTTP") for all requests, even when they're same-origin. I assume that's less efficient, but I don't know by how much. But given that browsers provide XHR for content scripts to use, it would be kind of dumb to use the background page for all requests just to fix Nature's insecure redirect.

**Comment by moddular** [comment]
H, sorry about this - the insecure redirect should be fixed now.

**Comment by dstillman** [comment]
Thanks!
