### ISSUE TITLE
Show small Z in all item type icons

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#298]
https://twitter.com/anthillsocial/status/1197451468397260800 and various forum threads from around the time of the 5.0 switchover, when Firefox users lost the 3-part button with the Z

**Comment by adomasven** [comment]
We could do a [badge](https://developer.chrome.com/extensions/browserAction#badge) with Zotero red background and white Z. That would be a very easy change. It wouldn't be exactly perfect in terms of our branding, but there's only so many pixels there anyway, and the other option is to reprocess all toolbar icons to include a more faithful Z

**Comment by adomasven** [comment]
I've been playing around with imagemagick to generate these and it looks...
![image](https://user-images.githubusercontent.com/5899315/84007233-bf5e0100-a978-11ea-990e-a346cb3338fb.png)
![image](https://user-images.githubusercontent.com/5899315/84007257-c7b63c00-a978-11ea-8ca7-8eed6bb074c4.png)
![image](https://user-images.githubusercontent.com/5899315/84007275-cdac1d00-a978-11ea-84bf-1f3f993d58af.png)
![image](https://user-images.githubusercontent.com/5899315/84007291-d43a9480-a978-11ea-81ab-fbc937fda6b5.png)
![image](https://user-images.githubusercontent.com/5899315/84007304-da307580-a978-11ea-8484-90e6dcb963ee.png)

Passable to horrible. I think no adding of background, resizing or shifting of icons-vs-badge will ultimately make this look good in the context of chrome badges. So here's the badge version:

![image](https://user-images.githubusercontent.com/5899315/84007835-a30e9400-a979-11ea-96df-95e490f3a4c5.png)
![image](https://user-images.githubusercontent.com/5899315/84007867-af92ec80-a979-11ea-9e70-c06d3db1c10a.png)
![image](https://user-images.githubusercontent.com/5899315/84007941-c5a0ad00-a979-11ea-88c5-fd15c8332a99.png)
![image](https://user-images.githubusercontent.com/5899315/84007951-cafdf780-a979-11ea-8334-acde92275616.png)
![image](https://user-images.githubusercontent.com/5899315/84007967-d0f3d880-a979-11ea-98e0-af53f3578cb5.png)

And even [better on Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setBadgeTextColor)!
![image](https://user-images.githubusercontent.com/5899315/84008208-2d56f800-a97a-11ea-8b64-43d4c46525c7.png)
![image](https://user-images.githubusercontent.com/5899315/84008249-3b0c7d80-a97a-11ea-805b-91a6211ef5dd.png)
![image](https://user-images.githubusercontent.com/5899315/84008285-4e1f4d80-a97a-11ea-8cc5-4cc6a1168474.png)
![image](https://user-images.githubusercontent.com/5899315/84008314-5b3c3c80-a97a-11ea-8678-5267519d00d2.png)
![image](https://user-images.githubusercontent.com/5899315/84008340-67c09500-a97a-11ea-90ad-0c3c73172f08.png)

Should we go ahead for the badge then?

P.S. Sorry for the misaligned screenshots

**Comment by flachware** [comment]
For reference, item type icons with integrated z.

![webpage](https://user-images.githubusercontent.com/419747/84019132-2d0e2b00-a981-11ea-80a5-c69f721eaaaf.png)
![newspaper-article](https://user-images.githubusercontent.com/419747/84019148-326b7580-a981-11ea-90ad-036c015dcf64.png)
![journal-article](https://user-images.githubusercontent.com/419747/84019165-35fefc80-a981-11ea-8c01-dad6d526f138.png)
![collection](https://user-images.githubusercontent.com/419747/84019176-38f9ed00-a981-11ea-9ec4-06a7aca47996.png)
![book](https://user-images.githubusercontent.com/419747/84019184-3bf4dd80-a981-11ea-92c8-b279f7d5f17a.png)

**Comment by adomasven** [comment]
Pushed as https://github.com/zotero/zotero-connectors/commit/27837248d3c91676029d512631e6926a1a64867d

**Comment by dstillman** [comment]
We could just use the chunkster:

<img width="160" alt="z-webpage" src="https://user-images.githubusercontent.com/783082/84127022-af8ffc80-aa0c-11ea-982f-0268212c5623.png">
<img width="127" alt="z-newspaperArticle" src="https://user-images.githubusercontent.com/783082/84127027-b1f25680-aa0c-11ea-8c11-c3616106da1d.png">
<img width="131" alt="z-journalArticle" src="https://user-images.githubusercontent.com/783082/84127039-b4ed4700-aa0c-11ea-8bde-dca87316ad41.png">
<img width="125" alt="z-folder" src="https://user-images.githubusercontent.com/783082/84127048-b74fa100-aa0c-11ea-82be-c25807a10f55.png">
<img width="131" alt="z-book" src="https://user-images.githubusercontent.com/783082/84127058-ba4a9180-aa0c-11ea-957f-4d56a7a7a93b.png">

**Comment by dstillman** [comment]
(Actually, that's not even pushed to the edge, but it could be.)

**Comment by dstillman** [comment]
We could also drop the opacity behind the Z a bit without making it white, just to give the Z a bit more contrast. This isn't even really noticeable — it just makes it a little easier to see the red:

<img width="16" src="https://user-images.githubusercontent.com/783082/84127923-dc90df00-aa0d-11ea-883c-1820fc85a6f0.png">

**Comment by anthonyjclark** [comment]
This seems to have been dropped. Badges were added in 2783724, but then that change was reverted in cd6d45a. Any chance the badges can be re-added since no images were proposed?

**Comment by adomasven** [comment]
Superseded by https://github.com/zotero/zotero-connectors/issues/503
