### ISSUE TITLE
Chrome Extension Shortcut

### ISSUE THREAD

**Issue by tommisaltiola** [zotero/zotero-connectors#302]
Zoteros shortcut ⌘ ⇧ S does not work for saving item to Zotero

I didnt find any way to get it working. What is wrong? Can it be fixed?

**Comment by tommisaltiola** [comment]
Very weird but once I changed the shortcut back and fourth several times it now works with ⇧ ⌘ S ...

**Comment by dstillman** [comment]
Please post support questions to the Zotero Forums at https://forums.zotero.org, where we're best able to help.
