### ISSUE TITLE
Translation fails when on-click permissions are enabled

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-connectors#317]
Report https://forums.zotero.org/discussion/84150/zotero-connector-function-broken-if-new-chrome-on-click-permission-set

**Comment by dsabsay** [comment]
I dug into this and discovered what is happening. When the extensions "Site access" mode is set to "On click" or "On specific sites", you still need to give it access to `http://127.0.0.1:23119/*`. I did this by temporarily switching it to "On specific sites", adding the localhost site, and then switching back to "On click" (my preferred setting).

When visiting a new domain, you must click the extension and reload the page before saving to Zotero will work (as expected). This seems to work and (on the outside) appears to be using my desired permissions. However, I did observe some odd behavior, described below.

Normally, the `chrome://extensions` page shows "Site access" is set to "On click" (as I requested). But from time to time, it will automatically change to "On specific sites". For example, this happens immediately after saving a page to Zotero. Usually, refreshing the `chrome://extensions` page causes it to go back to "On click". I'm not sure what to make of this. I suspect that adding an "allowed" site and then switching to "On click" mode has put something in a weird state. But from what I can tell, it's behaving in a reasonable way, i.e. using "On click" but automatically allowing the specific site I configured.

For clarity, here's the spot on `chrome://extensions` I'm talking about:
<img width="693" alt="Screen Shot 2022-01-02 at 6 43 46 PM" src="https://user-images.githubusercontent.com/11727932/147896891-fc91a299-4396-4c66-9d99-4f7cdc893cfa.png">
