### ISSUE TITLE
interceptKnownFileTypes pref checkbox doesn't reflect pref value

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#323]
https://forums.zotero.org/discussion/85094/automatic-file-importing-keeps-turning-itself-on

When `interceptKnownFileTypes` is unchecked, the Config Editor shows `false`, and interception stops as expected. However, reloading the prefs shows the checkbox as checked again, and calling `Zotero.Prefs.get('interceptKnownFileTypes')` in the page console for the prefs page returns `true`, even though `Zotero.Prefs.get('interceptKnownFileTypes')` in the background page returns `false`.

I assume this means that any boolean prefs that are evaluated in the page itself wouldn't work properly, but I'm not sure if we have any of those.

**Comment by adomasven** [comment]
In injected pages you either need to use `Zotero.Prefs.getAsync()` or for prefs that are loaded via code shared with the client where  pref retrieval is synchronous they need to be [pre-loaded](https://github.com/zotero/zotero-connectors/blob/015c47bcf018711673834fb4c0da81b0b92e40c7/src/common/zotero.js#L253-L254)
