### ISSUE TITLE
Can the Context Menu for Safari be hidden?

### ISSUE THREAD

**Issue by mzxwt** [zotero/zotero-connectors#348]
Can the Context Menu for Safari be hidden?
<img width="274" alt="截屏2021-03-14 下午12 43 44" src="https://user-images.githubusercontent.com/26818282/111057510-08705200-84c3-11eb-914c-4d2033ae3cef.png">

**Comment by dstillman** [comment]
Please post support questions to the [Zotero Forums](https://forums.zotero.org), where we're best able to help.
