### ISSUE TITLE
Add the Firefox connector to the official Firefox Addons site

### ISSUE THREAD

**Issue by Victor239** [zotero/zotero-connectors#349]
The [connectors page](https://www.zotero.org/download/connectors) only links to a direct download of the addon, which is a lot more sketchy than getting it from the official [Firefox Addons site](https://addons.mozilla.org/) and I'd feel safer getting it from there. I'm not sure if the direct downloaded version has auto-updates either.

**Comment by dstillman** [comment]
No, you're confused about this.

There's absolutely nothing "sketchy" about installing a browser extension directly from a known publisher. The Zotero Connector works with the Zotero app, which you also download from zotero.org and which has far more privileges than a WebExtension.

What matters is whether you trust the publisher. Zotero has been around for 15 years, is open source, is run by a non-profit organization, is recommended by most universities worldwide, and is used by millions of people. If you don't trust us, you shouldn't install any software from us. And the same goes for anything you find on AMO as well. Being on AMO is not a guarantee of safety.

Distributing the extension from zotero.org allows us to release updates, including critical bug fixes, days faster than we're able to for other browsers.
