### ISSUE TITLE
Safari: Unlocalized string errors in preferences

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#371]
https://forums.zotero.org/discussion/93751/save-to-zotero-with-pubmed-bug

I didn't try to reproduce, but doesn't seem like those errors should be there.

**Comment by adomasven** [comment]
I cannot reproduce this. I don't know what kind of build is currently deployed and whether it was built correctly, so it's hard to say what's caused it.

**Comment by adomasven** [comment]
Closing this was not reported again.
