### ISSUE TITLE
Chrome Connector is not lazy enough

### ISSUE THREAD

**Issue by christophe-dupriez** [zotero/zotero-connectors#374]
I am implementing embedding of COinS metadata in Microsoft Sharepoint Modern pages.

I succeed to generate the "spans" and to insert them based on the execution of the different web parts in the page. BUT the Zotero connector seems to look for COinS when the page initially loads and not when the user presses Ctrl-Shift-S. This is very annoying as the page content (and associated metadata) changes up to the moment the user ask a download to Zotero.

If this change conflicts with other, could it be triggered as an option.

What can I do to help?

**Comment by dstillman** [comment]
https://www.zotero.org/support/dev/exposing_metadata#force_zotero_to_refresh_metadata

**Comment by christophe-dupriez** [comment]
Thank you very much for your help. It is really appreciated.
