### ISSUE TITLE
Exports end up in wrong session on a terminal server

### ISSUE THREAD

**Issue by Sascha82x** [zotero/zotero-connectors#384]
On a Windows 2012 R2 terminal server, as soon as multiple logged-in users use the Zotero Conector via Firefox, the page ends up in some other user's library when clicked "Save to Zotero". Apparently the connector can't assign to which task it should send the page. The storage location set doesn't matter there.

Example:

User 1 and 2 start Zotero and Firefox. User 1 clicks on "Save to Zotero" in Firefox. The page ends up in user 2's image library.

**Comment by dstillman** [comment]
https://www.zotero.org/support/kb/multiple_instances

(Please [post all Zotero questions to the Zotero Forums](https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md).)
