### ISSUE TITLE
Show clearer error when trying to save from chrome-extension:// URL

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#386]
https://forums.zotero.org/discussion/97570/cannot-use-zotero-connector-for-pdfs and others

Any way we can detect these URLs and either extract the original PDF URL from the URL to send to Zotero or show a better error, instead of doing nothing? (Maybe not — I don't know that another extension can run at all on a chrome-extension:// URL.)

**Comment by adomasven** [comment]
We cannot show any UI in other extension pages. But we should show a disabled Z like we do in chrome:// pages there and not try to inject our scripts.

**Comment by dstillman** [comment]
What are we currently showing in the tooltip in this case? Can we show a distinct message for this? People are still going to be confused as to why they can't save PDFs.

**Comment by adomasven** [comment]
"Zotero is Offline/Online". We could say "Zotero is disabled on extension pages (Online/Offline)"?

**Comment by dstillman** [comment]
We don't need to say anything about online/offline here. "Zotero is disabled on extension pages" works.
