### ISSUE TITLE
SingleFile in Safari saves snapshots with JavaScript

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#398]
SingleFile on the Safari maintenance branch works great, but it appears to not be using our standard SingleFile config, since a snapshot saved from Safari runs JavaScript.

Reproduced on https://www.nytimes.com/2022/08/05/us/politics/medicare-drug-costs.html

**Comment by adomasven** [comment]
Fixed

**Comment by adomasven** [comment]
Not quite fixed yet it seems. Scripts are no longer saved, but we've also lost fonts and images. Non-paywall site to test: https://www.bbc.com/news/world-europe-62503775
