### ISSUE TITLE
Google search result links don't work if Safari connector and Tampermonkey are both enabled

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#404]
https://forums.zotero.org/discussion/100346/zotero-connector-tampermonkey-extension-breaks-links-on-google

> "SecurityError: The operation is insecure."
>
> Unsafe JavaScript attempt to initiate navigation for frame with URL '[https://www.google.com/search?q=test[…]'](https://www.google.com/search?q=test[%E2%80%A6]%27) from frame with URL '[https://www.google.com/url?sa=t[…]&url=https%3A%2F%2Fwww.merriam-webster.com%2Fdictionary%2Ftest[…].](https://www.google.com/url?sa=t[%E2%80%A6]&url=https%3A%2F%2Fwww.merriam-webster.com%2Fdictionary%2Ftest[%E2%80%A6].) The frame attempting navigation of the top-level window is cross-origin or untrusted and the user has never interacted with the frame."

@adomasven, any idea what's going on here?

**Comment by adomasven** [comment]
I've dsicovered that this is caused by the `single-file-hooks-frames.js` file from SingleFile and [reported it](https://github.com/gildas-lormeau/SingleFile/issues/1040).

**Comment by dstillman** [comment]
This isn't caused by `single-file-hooks-frames.js`. I can empty out all three files in `build/safari/lib/SingleFile`, including `single-file-hooks-frames.js`, and this still happens. It's fixed if I add an early return to [_injectSingleFileHooks()](https://github.com/zotero/zotero-connectors/blob/e96ba8192eaec59ae10acc4408e199c6e67d484e/src/common/singlefile.js#L67), but that doesn't have anything to do with SingleFile itself — I can change the path to `foo.js` and it still breaks.

**Comment by dstillman** [comment]
I've reported this to Tampermonkey.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero-connectors/commit/f01e95cd56c938cadf8bc9f5bd01dd3da8c849ea does fix this.
