### ISSUE TITLE
[Feature Request] Add a setting to use Zotero Web API to import online libraries in Google Docs

### ISSUE THREAD

**Issue by jooyoungseo** [zotero/zotero-connectors#424]
It would be so nice if there would be a setting to import my Zotero group libraries in Google Docs without having to open a local Zotero instance by providing Zotero web API.

**Comment by dstillman** [comment]
Please post feature requests and bug reports to the Zotero Forums.

https://github.com/zotero/zotero-connectors/blob/master/CONTRIBUTING.md

This is planned, but it's a major undertaking, since the entire citing interface is provided by the app.
