### ISSUE TITLE
SingleFile is hooking the IntersectionObserver API to detect and load deferred images.

### ISSUE THREAD

**Issue by sheldonmaschmeyer** [zotero/zotero-connectors#434]
I am having the same issue as [joshuahhh](https://forums.zotero.org/discussion/104701/zotero-connector-singlefile-is-hooking-the-intersectionobserver-api-warning)

This issue on first glance looks like an issue with the React (Vite dev server) web app but, disabling the Zotero extension in Chrome removes the warning.

![image](https://github.com/zotero/zotero-connectors/assets/22527914/9440451c-6f11-4b2a-b040-0df39707768a)

**Comment by adomasven** [comment]
Closed via https://github.com/zotero/zotero-connectors/commit/cfe07f5d61e6ee691ab3371fb2a6f67ca43ca549
