### ISSUE TITLE
Make the chrome extension compatible with Webextension (Firefox)

### ISSUE THREAD

**Issue by gagarine** [zotero/zotero-connectors#44]
[Webextension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) are the coming new extension for Firefox. Their are very similar to the Chrome extension and should be compatible.

I was able to load the Chrome Extension in Firefox by changing the manifest.json. Simply adding the key

	"applications": {
	  "gecko": {
	    "id": "zotero-connectors@zotero.org"
	  }
	},

I got the icon but nothings seem to append when I click on it.

This should help: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_from_Google_Chrome

**Comment by gagarine** [comment]
Great job :). How do we install this webextension in Firefox? Didn't find it on https://www.zotero.org/download/

**Comment by dstillman** [comment]
We haven't released the WebExtension version yet. (You can install it in a Firefox version that allows unsigned extensions by using a text proxy file in 'extensions' pointing to a build directory generated from the git repo, but if that doesn't make sense it's rather complicated to explain.)

**Comment by dstillman** [comment]
The Zotero Connector for Firefox <a href="https://www.zotero.org/download/">has been available</a> for months.
