### ISSUE TITLE
Translator not offered for PDF URL in Firefox

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#440]
https://forums.zotero.org/discussion/comment/438395/#Comment_438395
https://github.com/zotero/translators/pull/3079#issuecomment-1637146484

E.g., https://www.rfc-editor.org/rfc/rfc9406.pdf

Works in Chrome

**Comment by adomasven** [comment]
We can't run injected scripts in Firefox, so no translators. 

See https://github.com/zotero/zotero-connectors/issues/250

**Comment by dstillman** [comment]
Oh right.
