### ISSUE TITLE
Connector breaks JavaScript on some pages

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#441]
https://forums.zotero.org/discussion/107025/firefox-connector-breaks-javascript-on-certain-sites-report-id-610951252
https://forums.zotero.org/discussion/107031/zotero-chrome-connector-cause-js-errors-in-other-applications
https://forums.zotero.org/discussion/107032/zotero-connector-5-0-112-chrome
https://forums.zotero.org/discussion/107033/zotero-edge-connector-cause-js-errors-in-my-website

I reproduced the top two, in both Firefox and Chrome.

**Comment by Nixiak-nan** [comment]
Since 4am Beijing time on August 18, 2023, I have also encountered the same problem.
The js error message in the f12 console is as follows:
```Cannot read properties of null (reading 'nextSibling')```
```TypeError: Cannot read properties of null (reading 'insertBefore')```

**Comment by dstillman** [comment]
Now fixed: https://forums.zotero.org/discussion/comment/441308/#Comment_441308
