### ISSUE TITLE
vpat 38: citation successfully saved confirmation?

### ISSUE THREAD

**Issue by abaevbog** [zotero/zotero-connectors#469]
VPAT 38:

Description: When using the browser extension to save citations, there is no alert or non-visual indication that the citation has been successfully saved. This lack of confirmation can lead users to unintentionally duplicate citations, as they are unaware that the first attempt to save was successful. 

Impact Statement: Users relying on assistive technologies may become confused when citations are duplicated due to the absence of a notification confirming that a citation was successfully saved. An alert that can be read as text and dismissed through user interaction would help alleviate this issue. 

Expected Result: An alert appears visually and phonetically, informing the user that a citation was saved to the library successfully. 

Actual Result: Without confirmation, the user will likely attempt to save the citation again, resulting in duplicate entries with each additional save attempt.

---

I'm not sure what we could do about this. When the connector appears, I believe the item is essentially already saved, so the "Saving to ..." part is in itself a confirmation. In addition, unless I reload the page, opening the connector multiple times (and even hitting "Done" button repeatedly) does not lead to duplicate entries. I am not sure I see how adding a success message would makes sense here. @adomasven, correct me if I'm wrong on this and there is an appropriate way to fit some kind of confirmation here.

**Comment by dstillman** [comment]
Yes, this just seems like a misunderstanding. There's a success popup (which also allows changing the collection, but that's secondary), and it won't save again without a page reload.

The one thing I would want to check is whether we're assign a proper role (ARIA `alert` role?) to the save popup, so that it gets announced by screen readers.
