### ISSUE TITLE
RIS import progress window opens in new page unnecessarily

### ISSUE THREAD

**Issue by AbeJellinek** [zotero/zotero-connectors#491]
1. Open https://pubs.acs.org/doi/10.1021/acsaelm.4c00607, click RIS (top right under Export), Citation
2. Zotero confirmation dialog appears in the same tab. Click OK to import.
3. Import progress window appears on a new blank page, navigating you away from the page you were on.

If I understand the logic for showing the import progress window correctly, it should only show on a blank page when the originating page can't be used for some reason. But we're showing the confirmation dialog on the originating page, so it's not clear why navigating away is necessary in this case.

**Comment by adomasven** [comment]
Which browser are you seeing this on?

**Comment by dstillman** [comment]
I can reproduce this in Firefox.
