### ISSUE TITLE
This has been slowing down Gmail for the past several days

### ISSUE THREAD

**Issue by axfelix** [zotero/zotero-connectors#50]
Hi,

I would appreciate if someone can duplicate this, as it's just a theory at this point -- I think Gmail made a change to their js which is causing it to behave much more slowly when the Zotero Chrome extension is enabled. Not sure how easy it'll be to troubleshoot on this end...

**Comment by dstillman** [comment]
Yeah, we're aware of this. Should have a fix soon. Tracking here: https://github.com/zotero/zotero/issues/1021

**Comment by axfelix** [comment]
Aha -- thanks!

**Comment by dstillman** [comment]
Should be fixed in Chrome connector version 4.0.29.11, now available.
