### ISSUE TITLE
TypeError: Error in invocation of action.setIcon(object details, optional function callback): Error at parameter 'details': Error at property 'tabId': Value must be at least 0.

### ISSUE THREAD

**Issue by annosoo** [zotero/zotero-connectors#510]
zotero's icon in the browser is gone, and the document cannot be saved. The error is related to background.js

```Uncaught (in promise) TypeError: Error in invocation of action.setIcon(object details, optional function callback): Error at parameter 'details': Error at property 'tabId': Value must be at least 0.```

Here's the corresponding code in background.js
````
	function _showMessageButton(tab) {
		var icon = `${Zotero.platform}/zotero-z-32px-australis.png`;
		browser.action.setIcon({
			tabId: tab.id,
			path: `images/${icon}`
		});
		browser.action.setTitle({
			tabId: tab.id,
			title: "Zotero Connector"
		});
		browser.action.enable(tab.id);
	}
```

**Comment by adomasven** [comment]
Please post all feature requests and bug reports to the [Zotero Forums](https://forums.zotero.org). See [CONTRIBUTING.md](https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md) and [How Zotero Support Works](https://www.zotero.org/support/zotero_support) for more info.
