### ISSUE TITLE
Zotero Connector font can't be read whilst using a dark theme

### ISSUE THREAD

**Issue by Victor239** [zotero/zotero-connectors#514]
The text is white on a light background https://i.imgur.com/D5Al3dv.png

I tried posting this on the [forum](https://forums.zotero.org/discussion/118767/zotero-connector-font-cant-be-read-whilst-using-a-dark-theme?new=1) also but got no response.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero-connectors/blob/master/CONTRIBUTING.md

https://www.zotero.org/support/forum_guidelines#be_patient
