### ISSUE TITLE
Zotero crawls Google Scholar and only displays snapshots

### ISSUE THREAD

**Issue by r1ng13** [zotero/zotero-connectors#519]
<img width="1280" alt="Snipaste_2024-11-04_15-59-22" src="https://github.com/user-attachments/assets/943e6b66-57e5-4cfe-815f-a118c40c02d8">
<img width="1076" alt="2" src="https://github.com/user-attachments/assets/1cb66834-67ce-4520-8640-ab7ed24fa526">

As shown in the figure above, when using Zotero Connector to crawl documents in Google Scholar, you can only crawl a snapshot of the webpage, and cannot select the PDF of a specific document.

**Comment by adomasven** [comment]
Please post all feature requests and bug reports to the [Zotero Forums](https://forums.zotero.org). See [CONTRIBUTING.md](https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md) and [How Zotero Support Works](https://www.zotero.org/support/zotero_support) for more info.

**Comment by r1ng13** [comment]
thank you!
