### ISSUE TITLE
Progress window is not displayed on pages using framesets

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero-connectors#6]
https://github.com/zotero/zotero-connectors/blob/master/src/common/inject/progressWindow.js#L213 attempts to attach the progress window to document.body.

On pages that use frameset in place of body (e.g. http://ptx.sagepub.com/content/41/1/160.full.pdf+html?rss=1) the progress window DIV is appended to the frameset element, but per HTML5 specification it is not rendered (http://www.w3.org/html/wg/drafts/html/master/syntax.html#parsing-main-inframeset).

**Comment by adomasven** [comment]
Referenced URL no longer affected. If we run into this again we can reopen.
