### ISSUE TITLE
Restore Z before first click in Firefox

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#77]
My main concern in https://github.com/zotero/zotero-connectors/issues/72 was flashing during normal usage. To avoid scaring Z4Fx upgraders, I think we should still show the Z before the first click or client availability in Firefox.

**Comment by adomasven** [comment]
So this cannot be done without inducing flashing, as described in [the commit message](https://github.com/zotero/zotero-connectors/commit/273486f01398cd09994ec1b1333d9a2f224b373f). We would be flashing the webpage icon to Z for every reload. Certainly as distracting and will likely cause users to press the button early and not read the info page.
