### ISSUE TITLE
Direct PDF saving not working on proxied sites

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#89]
http://link.springer.com.mutex.gmu.edu/article/10.1007/s11153-004-8034-5

Not that you should, but if you click through to the PDF and try to save it directly, it gets a 500 error from Zotero due to an invalid PDF (`did not have MIME type 'application/pdf'`), presumably due to missing cookies or proxy info. (It also shows a confusing message about translators, which we should fix for direct PDF saving.)

https://forums.zotero.org/discussion/63962/5-0beta-save-pdf-to-zotero-translator-issues

**Comment by adomasven** [comment]
I have seen this before and just now in Chrome. Sometimes Springer Link serves a HTML page with JS redirection (possibly for bot prevention?).

http://www.jstor.org.mutex.gmu.edu/stable/j.ctt2jcvw0.10 works well, for example.
