### ISSUE TITLE
Long hang on Firefox startup with many saved tabs

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#94]
Without the Connector enabled, it takes 1m 15s on one system for the window to be ready (which seems worse than it used to be, but maybe I just have more tabs now…). With the Connector, it's 6.5 minutes.  This is many hundreds of tabs open and e10s disabled.

**Comment by adomasven** [comment]
I cannot reproduce on a fresh profile.

**Comment by dstillman** [comment]
Just another aspect of this, starting up a profile with hundreds of saved tabs with Zotero open, I get hundreds of /connector/ping requests, presumably one for every tab, even though they're not actually being loaded. Are we sure there's no other event to trigger on here that would only apply when the tab content is actually being loaded?

**Comment by stupidus89** [comment]
I made a possibly related observation. When the zotero connector is enabled, Firefox seems just generally to run a lot slower than when it is disabled. One way to reproduce it, seems to be to open a few tabs with random websites (~10-15 seems to be enough in my case), and then quickly closing them by spamming the middle mouse button on the tab bar. Once all the tabs are closed, the whole Firefox UI becomes unresponsive for around 10 seconds, if the zotero connector is enabled. If the zotero connector is disabled, this issue does not occur. I think I have to run more tests on this to be sure.

Other details: Firefox 55 on Arch Linux with a bunch of legacy extensions and the zotero connector being the only webextension

**Comment by gagarine** [comment]
@stupidus89 @dstillman still have the issue? Can you check on about:performance what's going on? Can you check on Firefox 57 beta?

I fell this was fixed upstream (on Firefox).

**Comment by dstillman** [comment]
No, I haven't really noticed this since before Firefox 56. (It's possible it's still a little bit slower than without the extension, but it's fast enough now that I haven't bothered to check.)

**Comment by dstillman** [comment]
And the slowness @stupidus89 was referring to was an unrelated issue that was indeed fixed in Firefox.

Closing this unless there are other reports.
