### ISSUE TITLE
Saving while feed selected works and saves to library.

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-connectors#95]
We should either correctly indicated that the item is being saved into "My Library" or prevent saving. The bug might be present for other configuration, where saving falls back to library, while showing a different selected collection.

**Comment by dstillman** [comment]
I think keeping the fallback and showing "My Library" makes sense.

**Comment by adomasven** [comment]
It does for feeds, but not sure for read-only group libraries. A fallback is better than an error, but may be slightly confusing.

**Comment by dstillman** [comment]
Oh, good point. Yeah, I don't think fallback is right for read-only group libraries, so if those are going to show an error, it's probably better to show the error across the board and keep clear the connection between what's selected in Zotero and saving from the connector (at least until we have a better solution for picking the destination).
