### ISSUE TITLE
Firefox's "Keep until: I close Firefox" cookie settings clear extension localStorage

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#96]
https://forums.zotero.org/discussion/comment/269043/#Comment_269043

I haven't confirmed this, but if true (which would make sense from a privacy perspective, because otherwise sites could just use localStorage to get around that setting), not sure there's anything to be done about this.

**Comment by dstillman** [comment]
Though arguably that shouldn't apply to the localStorage used by WebExtension, right?

**Comment by dstillman** [comment]
I actually can't reproduce this in 51.0.1.

**Comment by dstillman** [comment]
So in 51.0.1 I only see this with "Always use private browsing mode" enabled. More details here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1313401

**Comment by dstillman** [comment]
OK, it seems the difference was just that anything already set before enabling "Keep until: I close Firefox" remains after restart. If I manually clear localStorage and then enable that setting (but not "Always use private browsing mode"), I can reproduce this with just that setting.

It seems like this will need to be fixed in Firefox. I'm not sure what [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1313401#c4) means. Is there some storage that wouldn't be subject to this?

**Comment by adomasven** [comment]
> It seems like this will need to be fixed in Firefox. I'm not sure what this comment means. Is there some storage that wouldn't be subject to this?

[Browser Extension API storage](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage) is probably not subject to this. I.e. `browser.storage.local`/`browser.storage.sync`. I was considering that moving prefs for BrowserExt to use `browser.storage.local` would be desirable, but have not bothered with it as it wasn't very high priority.

**Comment by andersjohansson** [comment]
I believe you are right @adomasven, `browser.storage.local` seems the right way to go:
https://bugzilla.mozilla.org/show_bug.cgi?id=1317797#c1
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/local
(I'm also affected by this)

**Comment by stupidus89** [comment]
I am not sure if it is related. For privacy reasons I have `dom.storage.enabled` set to false. Currently, this means that I cannot use the zotero connector at all. Would the change to the extension storage API allow to use the Zotero connector without enabling dom.storage?

**Comment by Mathnerd314** [comment]
@andersjohansson  Are you sure it's not better to use [browser.storage.sync](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync)?

**Comment by dstillman** [comment]
Another report: https://forums.zotero.org/discussion/66666/zotero-connector-for-firefox-not-working
